### ISSUE TITLE
Vector -> ArrayList or List 으로 변경 고려

### ISSUE THREAD

**Issue by eeearl** [zja1vb2xj3/Notepad#1]
[RecyclerViewAdapter.java](https://github.com/zja1vb2xj3/Notepad/blob/master/app/src/main/java/com/example/user/notepad/RecyclerViewAdapter.java)
[MainActivity.java](https://github.com/zja1vb2xj3/Notepad/blob/master/app/src/main/java/com/example/user/notepad/MainActivity.java)

에서 사용중인 Vector 를 ArrayList 나 List 같은 상위 구현 클래스로 변경 고려

**Comment by zja1vb2xj3** [comment]
변경완료
