### ISSUE TITLE
메모를 여러번 생성시 이전에 입력했던 내용이 그대로 남아있음

### ISSUE THREAD

**Issue by eeearl** [zja1vb2xj3/Notepad#3]
![screenshot_1503330687](https://user-images.githubusercontent.com/6532026/29527537-240c2278-86d4-11e7-84f8-7de775a60e2b.png)
![screenshot_1503330689](https://user-images.githubusercontent.com/6532026/29527542-26bc254a-86d4-11e7-813c-fc4a7c7e9a77.png)

**Comment by zja1vb2xj3** [comment]
문제원인 Activity Stack 에 남아있는 RegisterNotepadActivity의 note_EditText 객체 메모리가 남아있어서 bug 가 생김 
멤버변수 note_EditText 객체의 선언부에 = null 을 할당하여 메모리 초기화 수행으로 해결
