### ISSUE TITLE
메모를 수정시 앱 종료됨

### ISSUE THREAD

**Issue by eeearl** [zja1vb2xj3/Notepad#4]
![screenshot_1503330865](https://user-images.githubusercontent.com/6532026/29527653-88553cc4-86d4-11e7-8eea-3ab3634914d0.png)

**Comment by zja1vb2xj3** [comment]
DBHelper

SQLiteDatabase 객체 .close() 로 생긴 오류로 추정 

Google에서 .close는 안해도 된다고 배움
