### ISSUE TITLE
리스트에서 롱클릭시 확인없이 삭제

### ISSUE THREAD

**Issue by eeearl** [zja1vb2xj3/Notepad#5]
다이얼로그로 삭제를 확인받거나
다른 종류의 방법으로 사용자가 실수로 삭제하는 일을 방지 해야할듯

**Comment by zja1vb2xj3** [comment]
MainActivity View에 할당된 RecyclerView 아이템 LongClick시 삭제물음 다이얼로그 생성으로 해결
 
RecyclerViewAdapter.class 의 OnItemLongClickListener.itemLongClick 메서드 의 return boolean 값에 따라서 removeViewItme 메서드 실행
